### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by schuerwm** [jayhogan/clicklist-client#5]
Is the API still supported.  I tried running the test code and receiving a timeout.  Thanks in advance

**Comment by johns10** [comment]
Yeah I'm looking at this as well.  I'm not very experienced with JS so I haven't tried this code, but I'm trying to duplicate this in python.  I can't even get basic 200 response and html out of a get request.  I've been able to get it working with postman, but not in python.  Any ideas what's going on here?  And how to get the site to respond properly to gets?

**Comment by johns10** [comment]
I've got the authentication workflow set up in python.  If anyone is interested in backporting to javascript, let me know .

**Comment by BrixSat** [comment]
Yes please provide the python code please. 

I am currently getting the access denied. Don't know why.... I'm outside America using America proxy. 

 Access Denied
You don't have permission to access "http://www.kroger.com/user/authenticate" on this server.

Any help would be appreciated.

**Comment by jayhogan** [comment]
The Kroger ClickList API is not documented for public use. The code I wrote is likely broken and any modification is likely to break again in the future. I've given up on creating a client library until Kroger creates a stable, public API.

Good luck everyone.
